import json

listOfCustoms = ["XMartian_Lamar_Jackson.png",
"XMartian_PC_Ssigned.png",
"xMartian_AirBorne.png",
"xMartian_Akeem.png",
"xMartian_AndrewForte.png",
"xMartian_Andy_Milonakis.png",
"xMartian_Anthony_Morrow.png",
"xMartian_BigBird.png",
"xMartian_Black_Excellence.png",
"xMartian_Brainiac.png",
"xMartian_Bsaic.png",
"xMartian_Captain_Booty_Signed.png",
"xMartian_Chief.png",
"xMartian_CoolJoe.png",
"xMartian_CryptoBully.png",
"xMartian_CryptoBully2.png",
"xMartian_CryptoCore.png",
"xMartian_CryptoCoreEuro.png",
"xMartian_CryptoCowboy_Signed.png",
"xMartian_CryptoGirl.png",
"xMartian_DFunch.png",
"xMartian_DaBaby.png",
"xMartian_Darcy_Donavan.png",
"xMartian_Darren.png",
"xMartian_DavidG.png",
"xMartian_DeFiBoy.png",
"xMartian_Dez.png",
"xMartian_Diablo.png",
"xMartian_Diablo_Signed.png",
"xMartian_Dom.png",
"xMartian_Drake.png",
"xMartian_Drill_Instructor.png",
"xMartian_Dutchess.png",
"xMartian_Enlighted.png",
"xMartian_FlavorsBSC.png",
"xMartian_FutureMattWallace.png",
"xMartian_Hangin.png",
"xMartian_ILove80s.png",
"xMartian_Intergalactic.png",
"xMartian_James.png",
"xMartian_Jay_Williams.png",
"xMartian_Jess.png",
"xMartian_John_Harding.png",
"xMartian_LG.png",
"xMartian_Lil_Wayne.png",
"xMartian_LisaJo.png",
"xMartian_LordNFT.png",
"xMartian_Lords_NFT_Signed.png",
"xMartian_Lords_Wifey_Signed.png",
"xMartian_LouThaWriter_Signed.png",
"xMartian_Marlon_Humphrey.png",
"xMartian_Martin.png",
"xMartian_Martin_Lawerence.png",
"xMartian_MattNFTy.png",
"xMartian_MoSanu.png",
"xMartian_MoneyMac.png",
"xMartian_MoonMark.png",
"xMartian_MoonMatt.png",
"xMartian_Ms.K.png",
"xMartian_Mutiat.png",
"xMartian_ObeyLord.png",
"xMartian_Obi.png",
"xMartian_Original41.png",
"xMartian_PC2.png",
"xMartian_Papa_Signed.png",
"xMartian_Pink_LegoFrames.png",
"xMartian_Puff_Daddy.png",
"xMartian_RedSwag.png",
"xMartian_RickGrimm_signed.png",
"xMartian_Ricky_Williams.png",
"xMartian_Safepool.png",
"xMartian_Shiggy.png",
"xMartian_Skye.png",
"xMartian_SmokeOut.png",
"xMartian_Snoop_Dog.png",
"xMartian_Sophie.png",
"xMartian_SoulTrippas.png",
"xMartian_SpaceKitty.png",
"xMartian_SpacedOut.jpeg",
"xMartian_Stealie.png",
"xMartian_Swag.png",
"xMartian_Swift.png",
"xMartian_Tech_Signed.png",
"xMartian_Tre_Songz.png",
"xMartian_Trevon_Diggs.png",
"xMartian_Tristan_Jass.png",
"xMartian_Uncle_Paulie.png",
"xMartian_VaultDeFiJenn.png",
"xMartian_Viking.png",
"xMartian_VonMiller.png",
"xMartian_Woods.png",
"xMartian_ZZZ.jpeg",
"xMartian_original29.png"]

tempJSON = {
    "attributes": [
        {
            "trait_type": "Martian Type",
            "value": "Super Rare"
        }
    ],
    "description": "xMartian Collection One",
    "external_url": "https://xMartianNFT.com/1",
    "image": "https://gateway.pinata.cloud/ipfs/QmQ8R3mSV7kefGJmWJuRqNdLANTAzR6g2h7qedX3ai6uPg/",
    "name": "xMartian00001"
}

for customImg in listOfCustoms:
    tempJSON["name"] = customImg
    tempJSON["image"] = "https://gateway.pinata.cloud/ipfs/QmQ8R3mSV7kefGJmWJuRqNdLANTAzR6g2h7qedX3ai6uPg/" + tempJSON["name"],
    finalJSON = json.dumps(tempJSON, indent=4)
    with open('src/output/newJSON/' + tempJSON["name"] + '.json', 'w') as output_file:
        output_file.write(finalJSON) 